server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: FEBS-Register
  #受保护资源所需的用户名和密码
  security:
    user:
      name: febs
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456


eureka:
  instance:
    hostname: localhost
  client:
    #是否将服务注册到注册中心，单节点false
    register-with-eureka: false
    #是否从注册中心获取信息，单节点 false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
